AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CI/CD pipeline for GitHub projects

Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'PK'
          AttributeType: 'S'
        -
          AttributeName: 'SK'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'PK'
          KeyType: 'HASH'
        -
          AttributeName: 'SK'
          KeyType: 'RANGE'
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "AuctionsTable"

  AuctionGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: AuctionsAPI
      StageName: prod
  # Auction Lambda Functions
  CreateAuctionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that creates auction entity
      CodeUri: backend/functions/api/auction/createAuction
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /auction
              Method: post
              RestApiId:
                Ref: AuctionGateway