AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CI/CD pipeline for GitHub projects

Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'PK'
          AttributeType: 'S'
        -
          AttributeName: 'SK'
          AttributeType: 'S'
        - 
          AttributeName: 'GSI1PK'
          AttributeType: 'S'
        -
          AttributeName: 'GSI1SK'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'PK'
          KeyType: 'HASH'
        -
          AttributeName: 'SK'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: 'HASH'
            - AttributeName: GSI1SK
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        # - IndexName: GSI2
        #   KeySchema:
        #     - AttributeName: GSI2PK
        #       KeyType: HASH
        #     - AttributeName: GSI2SK
        #       KeyType: RANGE
        #   Projection:
        #     ProjectionType: ALL
        #   ProvisionedThroughput: 
        #     ReadCapacityUnits: "5"
        #     WriteCapacityUnits: "5"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "AuctionsTable"

  AuctionGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: AuctionsAPI
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'X-Amz-Date,X-Api-Key,X-Amz-Security-Token,access_token,X-Requested-With,X-Auth-Token,Referer,User-Agent,Origin,Content-Type,Authorization,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
  # Auction Lambda Functions
  CreateAuctionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that creates auction entity
      CodeUri: backend/functions/api/auction/createAuction
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /auction
              Method: post
              RestApiId:
                Ref: AuctionGateway

  GetAuctionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that gets auction entity
      CodeUri: backend/functions/api/auction/getAuction
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /auctions/{auctionId}
              Method: get
              RestApiId:
                Ref: AuctionGateway

  GetAuctionListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that gets auction entity
      CodeUri: backend/functions/api/auction/getAuctionList
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Scan
              - dynamodb:GetItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /auctionsList
              Method: get
              RestApiId:
                Ref: AuctionGateway

  FinishAuctionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that finishes auction
      CodeUri: backend/functions/api/auction/finishAuction
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /auctions/{auctionId}/finish
              Method: post
              RestApiId:
                Ref: AuctionGateway
  # Item Lambda Functions
  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that creates item entity
      CodeUri: backend/functions/api/item/createItem
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /item
              Method: post
              RestApiId:
                Ref: AuctionGateway

  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that gets item entity
      CodeUri: backend/functions/api/item/getItem
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /items/{itemId}
              Method: get
              RestApiId:
                Ref: AuctionGateway
  
  GetItemListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that gets auction entity
      CodeUri: backend/functions/api/item/getItemList
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Scan
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /itemsList
              Method: get
              RestApiId:
                Ref: AuctionGateway

  GetUserItemListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that gets user items
      CodeUri: backend/functions/api/item/getUserItems
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Query
            Resource: 
              - !GetAtt DynamoDBTable.Arn
              - Fn::Sub:
                  - '${DynamoDBTableArn}/index/GSI1'
                  - DynamoDBTableArn: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /user/{userId}/items
              Method: get
              RestApiId:
                Ref: AuctionGateway

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that creates user entity
      CodeUri: backend/functions/api/user/createUser
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /user
              Method: post
              RestApiId:
                Ref: AuctionGateway

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      AutoPublishAlias: live
      Tracing: Active
      MemorySize: 512
      Timeout: 15
      Description: Lambda function that authorizes user
      CodeUri: backend/functions/authorizer
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        ApiEvent:
            Type: Api
            Properties:
              Path: /authorize
              Method: post
              RestApiId:
                Ref: AuctionGateway