version: 0.2

env:
  variables:
    GO111MODULE: "on"

phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - ls
      - export ROOTDIR=`pwd`
      # Build CreateAuctionFunction
      - cd $ROOTDIR/backend/functions/api/auction/createAuction
      - go build -o main

      # Build GetAuctionFunction
      - cd $ROOTDIR/backend/functions/api/auction/getAuction
      - go build -o main

      # Build GetAuctionListFunction
      - cd $ROOTDIR/backend/functions/api/auction/getAuctionList
      - go build -o main

      # Build FinishAuctionFunction
      - cd $ROOTDIR/backend/functions/api/auction/finishAuction
      - go build -o main

      # Build CreateItemFunction
      - cd $ROOTDIR/backend/functions/api/item/createItem
      - go build -o main

      # Build GetItemFunction
      - cd $ROOTDIR/backend/functions/api/item/getItem
      - go build -o main

      # Build GetItemListFunction
      - cd $ROOTDIR/backend/functions/api/item/getItemList
      - go build -o main

      - cd $ROOTDIR
      - echo ${PACKAGE_BUCKET}
      - aws cloudformation package --template-file backend_resources.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged-backend_resources.yaml
artifacts:
  files:
    - packaged-backend_resources.yaml