version: 0.2

env:
  variables:
    GO111MODULE: "on"

phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - ls
      - export ROOTDIR=`pwd`
      # Build CreateAuctionFunction
      - cd $ROOTDIR/backend/functions/api/auction/createAuction
      - go build -o main

artifacts:
  files:
    - backend_resources.yaml