version: 0.2

env:
  variables:
    GO111MODULE: "on"

phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - ls
      - export ROOTDIR=`pwd`
      # Build CreateAuctionFunction
      - cd $ROOTDIR/backend/functions/api/auction/createAuction
      - go build -o main

      - cd $ROOTDIR
      - aws cloudformation package --template-file backend_resources.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file backend_resources.yaml
artifacts:
  files:
    - backend_resources.yaml