version: 0.2

env:
  variables:
    GO111MODULE: "on"

phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - ls
      - export ROOTDIR=`pwd`
      # Build CreateAuctionFunction
      - cd $ROOTDIR/backend/functions/api/auction/createAuction
      - go build -o main

      # Build GetAuctionFunction
      - cd $ROOTDIR/backend/functions/api/auction/getAuction
      - go build -o main

      # Build GetAuctionListFunction
      - cd $ROOTDIR/backend/functions/api/auction/getAuctionList
      - go build -o main

      # Build SearchAuctionsFunction
      - cd $ROOTDIR/backend/functions/api/auction/searchAuctions
      - go build -o main

      # Build CreateItemFunction
      - cd $ROOTDIR/backend/functions/api/item/createItem
      - go build -o main

      # Build UpdateAuctionFunction
      - cd $ROOTDIR/backend/functions/api/auction/updateAuction
      - go build -o main

      # Build DeleteAuctionFunction
      - cd $ROOTDIR/backend/functions/api/auction/deleteAuction
      - go build -o main

      # Build GetItemFunction
      - cd $ROOTDIR/backend/functions/api/item/getItem
      - go build -o main

      # Build DeleteItemFunction
      - cd $ROOTDIR/backend/functions/api/item/deleteItem
      - go build -o main

      # Build SearchItemsFunction
      - cd $ROOTDIR/backend/functions/api/item/searchItems
      - go build -o main

      # Build UpdateItemFunction
      - cd $ROOTDIR/backend/functions/api/item/updateItem
      - go build -o main

      # Build CreateUserFunction
      - cd $ROOTDIR/backend/functions/api/user/createUser
      - go build -o main

      # Build PatchUserFunction
      - cd $ROOTDIR/backend/functions/api/user/updateUser
      - go build -o main

      # Build AuthorizerFunction
      - cd $ROOTDIR/backend/functions/authorizer
      - go build -o main

      # Build GetUserItemsFunction
      - cd $ROOTDIR/backend/functions/api/item/getUserItemsList
      - go build -o main

      # Build GetUserByIDFunction
      - cd $ROOTDIR/backend/functions/api/user/getUserByID
      - go build -o main

      # Build GetAuctionBidsFunction
      - cd $ROOTDIR/backend/functions/api/bid/getAuctionBids
      - go build -o main

      # Build PlaceAuctionBidFunction
      - cd $ROOTDIR/backend/functions/api/bid/placeBid
      - go build -o main

      # Build HandleAuctionFunction
      - cd $ROOTDIR/backend/functions/eventbridge/auctionWorker
      - go build -o main

      # Build HandleBidFunction
      - cd $ROOTDIR/backend/functions/eventbridge/bidWorker
      - go build -o main

      - cd $ROOTDIR
      - echo ${PACKAGE_BUCKET}
      - aws cloudformation package --template-file backend_resources.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged-backend_resources.yaml
artifacts:
  files:
    - packaged-backend_resources.yaml