AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CFNStackName:
    Description: stack name
    Type: String
    Default: test
Resources:
  CloudFormationRole:
    Type: AWS::IAM::Role
    # checkov:skip=CKV_AWS_109:Ensure IAM policies does not allow permissions management without constraints
    Properties:
      RoleName: !Sub '${CFNStackName}-cloudformation-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Sid: ''
            Principal:
              AWS: '*'
            Condition:
              StringLike:
                'aws:PrincipalArn':
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/test-CodePipelineServiceRole*
            Action: sts:AssumeRole

      Policies:
        - PolicyName: CodePipelineServiceRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              ################### cloudformation ###################
              - Effect: Allow
                Action:
                  - cloudformation:DescribeChangeSet
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                Resource:
                  - !Sub 'arn:aws:cloudformation:us-east-1:*:stack/${CFNStackName}*'
                  - arn:aws:cloudformation:us-east-1:aws:transform/Serverless-2016-10-31
                  - arn:aws:cloudformation:us-east-1:aws:transform/Include
              ################### s3 ###################
              - Effect: Allow
                Action:
                  - s3:PutObject*
                  - s3:GetObject
                Resource: '*'

              - Effect: Allow
                Action:
                  - s3:DeleteBucket
                  - s3:ListBucket
                Resource: '*'

              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:PutLifecycleConfiguration
                  - s3:GetLifecycleConfiguration
                  - s3:GetEncryptionConfiguration
                  - s3:PutEncryptionConfiguration
                  - s3:GetObjectAcl
                  - s3:PutObjectAcl
                  - s3:PutBucketTagging
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketLocation
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PassRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                Resource: '*'
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:CreateTable
                  - dynamodb:DeleteTable
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:UpdateTimeToLive
                Resource: '*'
              - Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:GetFunction
                  - lambda:CreateEventSourceMapping
                  - lambda:GetEventSourceMapping
                  - lambda:DeleteEventSourceMapping 
                  - lambda:GetFunctionCodeSigningConfig
                  - lambda:GetFunctionConfiguration
                  - lambda:DeleteFunction
                  - lambda:AddPermission
                  - lambda:UpdateFunctionCode
                  - lambda:ListTags
                  - lambda:TagResource
                  - lambda:InvokeFunction
                  - lambda:UntagResource
                  - lambda:ListVersionsByFunction
                  - lambda:PublishVersion
                  - lambda:CreateAlias
                  - lambda:DeleteAlias
                  - lambda:RemovePermission
                  - lambda:GetAlias
                  - lambda:UpdateAlias
                  - lambda:UpdateFunctionConfiguration
                Resource: '*'
              - Effect: Allow
                Action:
                  - apigateway:PATCH
                  - apigateway:POST
                  - apigateway:GET
                  - apigateway:DELETE
                  - apigateway:PUT
                  - apigateway:UpdateRestApiPolicy
                Resource: '*'

